// Generated by CoffeeScript 1.7.1
(function() {
  window.PB = {};

  PB.Drum = (function() {
    function Drum() {}

    return Drum;

  })();

  PB.GridLine = (function() {
    function GridLine(prefix) {}

    return GridLine;

  })();

}).call(this);
